### ISSUE TITLE
Device Grouping - Home-assistant

### ISSUE THREAD

**Issue by somejavadev** [gtricot/docker-lechacal-homeassistant#3]
Hi,

I have made a couple of changes to the code over the weekend and migrated it to your fork.

The changes include having the LeChacal Energy Monitor show up as a device under Home Assistant:

![image](https://user-images.githubusercontent.com/6507120/119373958-4c4cb800-bcb9-11eb-87d5-174c91ef7735.png)

The different sensors (entities) are then also grouped along this device:

![image](https://user-images.githubusercontent.com/6507120/119374062-6ab2b380-bcb9-11eb-8f77-3e69e436492d.png)

Selecting one sensor (entity) will then show you the related entities in home assistant:

![image](https://user-images.githubusercontent.com/6507120/119374191-946bda80-bcb9-11eb-9a6f-1aeb710a5e68.png)   
   
The changes I have made is mostly done with the initial config message. You will see I have also added the 'availability' options to detect when the sensor hasn't received data in roughly 5 minutes.  This mechanism is really basic but will flag the sensors on home-assistant as 'Unavailable' if no serial messages has come through.  
  

I will create a pull request if you are interested in the changes, the names of the topics can be updated if required, currently they are just the ones I chose.   

Other changes I have made are adding a systemd startup script to ensure the service starts when the pi is rebooted, adding a docker-compose file that uses the new environment variables, documenting docker-compose install on a raspberry pi zero.  

Let me know if you are interested in any of these.

**Comment by gtricot** [comment]
Hi,

I merged your PR #4, so I will close that issue.

Personally, I don't plan to use the systemd startup script, neither the docker-compose (my LeChacal device is installed on the same Raspberry 4B than Home Assistant, and the docker-lechacal-homeassistant image is running on HASS OS, without docker-compose, but with "--restart always" option), but feel free to create another PR, it could help someone else !

Thank's for your contribution.
